name: app
description: Application Performance Monitoring (APM)
publish_to: 'none'
version: 0.0.1
homepage: https://github.com/PlugFox/apm


environment:
  sdk: '>=2.19.2 <4.0.0'
  flutter: '>=3.7.5'


dependencies:
  # Flutter SDK
  flutter:
    sdk: flutter

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: any

  # Utils
  collection: any
  async: any
  meta: any

  # Desktop
  #bitsdojo_window: ^0.1.5
  window_manager: ^0.3.1

  # Packages
  database:
    path: package/database
  server:
    path: package/server
  entity:
    path: package/entity


dev_dependencies:
  # Unit & Widget tests for Flutter
  flutter_test:
    sdk: flutter
  # Integration tests for Flutter
  integration_test:
    sdk: flutter

  # Linting
  flutter_lints: ^2.0.0

  # Codegen
  build_runner: ^2.3.3
  flutter_launcher_icons: any
  flutter_native_splash: any
  pubspec_generator: any
  flutter_gen_runner: any


flutter:
  uses-material-design: true


flutter_intl:
  enabled: true
  class_name: GeneratedLocalization
  main_locale: en
  arb_dir: lib/src/common/localization
  output_dir: lib/src/common/localization/generated
  use_deferred_loading: false


flutter_gen:
  output: lib/src/common/constant/
  line_length: 120
