name: database
description: SQLite database
version: 0.0.1

publish_to: "none"

environment:
  sdk: '>=2.19.2 <4.0.0'

dependencies:
  drift: ^2.5.0
  meta: ^1.7.0
  multiline: ^3.0.0
  path: ^1.8.1
  path_provider: ^2.0.11
  sqlite3_flutter_libs: ^0.5.13

dev_dependencies:
  build_runner: ^2.3.3
  drift_dev: ^2.5.2
  lint: ^2.0.1
  file: ^6.1.4
