include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - "lib/**.g.dart"

  # Enable the following options to enable strong mode.
  language:
    strict-casts: true
    strict-raw-types: true
    strict-inference: true

  # Enable the following options to enable new language features.
  #enable-experiment:
  #  - patterns
  #  - sealed-class
  #  - records
  #  - class-modifiers
  #  - macros
  #  - const-functions
  #  - extension-types
  #  - inference-update-2
  #  - inline-class
  #  - value-class
  #  - variance

  # Set the following options to true to enable additional analysis.
  errors:
    # Info
    directives_ordering: info
    always_declare_return_types: info

    # Warning
    unsafe_html: warning
    no_logic_in_create_state: warning
    empty_catches: warning
    close_sinks: warning

    # Error
    prefer_relative_imports: error
    avoid_relative_lib_imports: error
    avoid_slow_async_io: error
    avoid_types_as_parameter_names: error
    cancel_subscriptions: error
    valid_regexps: error
    always_require_non_null_named_parameters: error

    # Disable rules

# Lint rules
linter:
  rules:
    # Public packages
    public_member_api_docs: false
    lines_longer_than_80_chars: false

    # Enabling rules
    prefer_relative_imports: true
    avoid_relative_lib_imports: true

    # Disable rules
    sort_pub_dependencies: false
    always_use_package_imports: false