name: server
description: Server
version: 0.0.1

publish_to: "none"

environment:
  sdk: '>=2.19.2 <4.0.0'

dependencies:
  meta: ^1.7.0
  path: ^1.8.1
  path_provider: ^2.0.11

  # Utils
  crypto: ^3.0.2
  protobuf: ^2.1.0

  # Web server
  shelf: any
  shelf_web_socket: any
  web_socket_channel: any

  # Entities
  entity:
    path: ../entity

dev_dependencies:
  test: any
  build_runner: ^2.3.3
  lint: ^2.0.1
  file: ^6.1.4
